### ISSUE TITLE
Cursor not following the inserted text if the text is longer than the width of the input field

### ISSUE THREAD

**Issue by Mari0** [y-js/y-text#3]
In Chrome 51 if i bind a html-input field to y-text and insert text. If i reach the right border of the input field the cursor is not following the inserted text like it should. Basically i write out of the visible region and the cursor is not following. 
I just binded a input-html field to y.text as is the examples of [Yjs](http://y-js.org/#!/examples):
`y.share.text.bind(document.getElementById('test'));`

In Firefox its is working.

**Comment by dmonad** [comment]
This bug is also reported on the chromium bug-tracker: [link](https://bugs.chromium.org/p/chromium/issues/detail?id=331233)

A patch was already created and you can expect to see this soon in Chrome & Chromium (I guess..). I tested a lot on how to solve this problem now. I found one solution, that will overwrite the browser behavior on scrolling in input areas. For this reason I won't implement it directly in y-text. But you can use it now:

```
function fixScrolling (input) {
  var oldHandler = input.onkeydown
  input.onkeydown = function () {
    if (oldHandler != null) oldHandler.apply(this, arguments)
    input.scrollLeft = Math.floor((input.selectionStart / input.value.length) * input.scrollWidth)
  }
}
```

##### Use it for input elements:

`fixScrolling(document.querySelector('#myInput'))`

_Note:_ This is not a really good solution. Unfortunately I can't think of a good solution until Chrome fixed this issue..
