### ISSUE TITLE
y-text returns \n on single line html-input fields

### ISSUE THREAD

**Issue by Mari0** [y-js/y-text#5]
Hi Kevin,
if i type  enter (\n) in a html-input field binded to a ytext and retrieve the value using`ytext.toString()` the String consits of "\n". 
It's not a big problem i can filter it out with `ytext.toString().replace(/\n/g,'')`, but for a single line input field I think "\n" shouldn't occur there.

I tested in older SyncMeta version which uses y-text 9.0.1 and yjs 11.2.6 and the newest which uses the latest versions(yjs 12.0.4 and y-text 9.0.2).
Best,
Mario

**Comment by dmonad** [comment]
Thanks for bringing this up. I am going to rework the implementation of this type. Currently, my implementation is not (and should not be) aware of the type of object it receives events from. I have some ideas for a better implementation: I am going to use text diffs instead of listening to browser events. Therefore, the new implementation should have the described behavior, and will fix #4

I have other things to do right now, so I will fix this in ~ one week.

**Comment by dmonad** [comment]
Implemented in v9.1
